name: Request.ForecastWeather
author: thinkphp
current: 1.0 
category: widgets  
tags:  [request,badge,weather,forecast,yql,jsonp,widget]
docs:  http://github.com/thinkphp/Request.ForecastWeather/blob/24ae53b74389d32e06d0a19bcb550694c321eef7/Docs/Request.ForecastWeather.md
demo:  http://thinkphp.ro/apps/js-hacks/Request.Weather/ 